steps:
    - name: 'lucaslz/cloud-builders/docker'
      args: ['build','-t','lucaslz/fullcycle-exemplos/live-ci-cd:latest', '-t','lucaslz/fullcycle-exemplos/live-ci-cd:$SHORT_SHA','.']

    - name: 'docker'
      args: ['run','-d','--name','goapp','lucaslz/fullcycle-exemplos/live-ci-cd:latest']

    - name: 'docker'
      args: ['exec', 'goapp', 'go', 'test']

    # - name: 'docker'
    #   args: ['push', 'lucaslz/fullcycle-exemplos/live-ci-cd:latest']

    # - name: 'docker'
    #   args: ['push', 'lucaslz/fullcycle-exemplos/live-ci-cd:$SHORT_SHA']