steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','lucaslz/fullcycle-exemplos/live-ci-cd:latest', '-t','lucaslz/fullcycle-exemplos/live-ci-cd:$SHORT_SHA','.']

    - name: 'docker'
      args: ['run','-d','--name','goapp','lucaslz/fullcycle-exemplos/live-ci-cd:latest']

    - name: 'docker'
      args: ['exec', 'goapp', 'go', 'test']

    - name: 'docker'
      args: ['push', 'lucaslz/fullcycle-exemplos/live-ci-cd:latest']

    - name: 'docker'
      args: ['push', 'lucaslz/fullcycle-exemplos/live-ci-cd:$SHORT_SHA']

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run','deploy','go-cloudrun','--image','lucaslz/fullcycle-exemplos/live-ci-cd:$SHORT_SHA','--region','us-central1','--platform','managed','--allow-unauthenticated']